### ISSUE TITLE
Odunculuk Sistemi

### ISSUE THREAD

**Issue by erenbulbul** [hsndmrts/RPG#3]
**Oduncular:**
Odun kırdıklarında 2-3 tane çubuk düşer. Odun Düşmez.
/Oduncu komutu ile açılan menüde oduncular üretim yapabilir.
Oduncu menüsünde üretilebilecekler:
1 Tahta - Gerekenler (9 Çubuk, 2 Tecrübe)
1 Odun - Gerekenler (4 Tahta, 9 Tecrübe)
1 Çit - Gerekenler (4 Çubuk, 1 Tecrübe)
1 Tahta merdiven - Gerekenler (1 Tahta, 10 Tecrübe)
1 Tahta Kapı - Gerekenler (6 Tahta, 20 Tecrübe)
1 Tabela - Gerekenler (1 Tahta, 1 Çubuk, 1 Tecrübe)

Her dakika, Oduncuya 3 tecrübe gelir.
Oduncular /Tecrübe komutu ile tecrübesini sorgulayabilir.

**Oduncu Mesleğine Sahip Olmayanlar:**
Odun kırdıklarında 0-1 tane çubuk düşer. Odun düşmez.
El ile kırarlar ise sadece %10 şansla 1 adet çubuk düşer.
Her odun kırışlarından sonra "Sen oduncu değilsin ! Odunları verimli kıramazsın !" yazısı çıkar.

**Comment by Dougladd** [comment]
+1

**Comment by hsndmrts** [comment]
tahta ney? odunu craft a koyunca çıkan 4 tane plaka mı?

**Comment by erenbulbul** [comment]
Evet tahta blok.

**Comment by hsndmrts** [comment]
anladım
